name: 
title: GCP InSpec Profile
maintainer: TaEduard
license: MIT
summary: An InSpec Compliance Profile For GCP
version: 0.1.0
inspec_version: '>= 2.3.5'
attributes:
- name: gcp_project_id
  required: true
  description: 'The GCP project identifier.'
  type: string
depends:
- name: inspec-gcp
  url: https://github.com/inspec/inspec-gcp/archive/master.tar.gz
supports:
- platform: gcp